/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AcademicYearSchema extends BaseModel {
  static $columns = ['createdAt', 'endDate', 'id', 'isCurrent', 'name', 'startDate', 'updatedAt'] as const
  $columns = AcademicYearSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isCurrent: boolean | null
  @column()
  declare name: string
  @column.date()
  declare startDate: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AssessmentSchema extends BaseModel {
  static $columns = ['academicYearId', 'classId', 'createdAt', 'date', 'id', 'maxScore', 'subjectId', 'teacherId', 'title', 'type', 'updatedAt'] as const
  $columns = AssessmentSchema.$columns
  @column()
  declare academicYearId: number | null
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxScore: number | null
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AssignmentSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'description', 'dueDate', 'id', 'instructions', 'maxScore', 'status', 'subjectId', 'teacherId', 'title', 'updatedAt'] as const
  $columns = AssignmentSchema.$columns
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.dateTime()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instructions: string | null
  @column()
  declare maxScore: number | null
  @column()
  declare status: string | null
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AttendanceSchema extends BaseModel {
  static $columns = ['classId', 'comment', 'createdAt', 'date', 'id', 'justification', 'status', 'studentId', 'updatedAt'] as const
  $columns = AttendanceSchema.$columns
  @column()
  declare classId: number | null
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare date: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare justification: boolean | null
  @column()
  declare status: string
  @column()
  declare studentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ClassSchema extends BaseModel {
  static $columns = ['academicYearId', 'createdAt', 'id', 'levelId', 'name', 'optionId', 'prefectId', 'updatedAt'] as const
  $columns = ClassSchema.$columns
  @column()
  declare academicYearId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare levelId: number | null
  @column()
  declare name: string
  @column()
  declare optionId: number | null
  @column()
  declare prefectId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CourseSchema extends BaseModel {
  static $columns = ['classId', 'content', 'createdAt', 'description', 'id', 'subjectId', 'teacherId', 'title', 'updatedAt'] as const
  $columns = CourseSchema.$columns
  @column()
  declare classId: number | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EnrollmentSchema extends BaseModel {
  static $columns = ['academicYearId', 'classId', 'createdAt', 'enrollmentDate', 'id', 'status', 'studentId', 'updatedAt'] as const
  $columns = EnrollmentSchema.$columns
  @column()
  declare academicYearId: number | null
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare enrollmentDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column()
  declare studentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EvaluationSchema extends BaseModel {
  static $columns = ['courseId', 'createdAt', 'description', 'evaluationDate', 'id', 'maxScore', 'title', 'updatedAt'] as const
  $columns = EvaluationSchema.$columns
  @column()
  declare courseId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column.dateTime()
  declare evaluationDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare maxScore: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GradeSchema extends BaseModel {
  static $columns = ['assessmentId', 'comment', 'createdAt', 'id', 'score', 'studentId', 'updatedAt'] as const
  $columns = GradeSchema.$columns
  @column()
  declare assessmentId: number | null
  @column()
  declare comment: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: number
  @column()
  declare studentId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LevelSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = LevelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OptionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = OptionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ScheduleSchema extends BaseModel {
  static $columns = ['classId', 'createdAt', 'dayOfWeek', 'endTime', 'id', 'room', 'startTime', 'subjectId', 'teacherId', 'updatedAt'] as const
  $columns = ScheduleSchema.$columns
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dayOfWeek: string
  @column()
  declare endTime: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare room: string | null
  @column()
  declare startTime: string
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SchoolSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'description', 'email', 'facebook', 'history', 'id', 'instagram', 'logo', 'name', 'objectives', 'phone', 'updatedAt', 'website'] as const
  $columns = SchoolSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare email: string | null
  @column()
  declare facebook: string | null
  @column()
  declare history: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare instagram: string | null
  @column()
  declare logo: string | null
  @column()
  declare name: string
  @column()
  declare objectives: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare website: string | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'dateOfBirth', 'enrollmentDate', 'gender', 'id', 'status', 'studentNumber', 'updatedAt', 'userId'] as const
  $columns = StudentSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime | null
  @column.date()
  declare enrollmentDate: DateTime | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string | null
  @column()
  declare studentNumber: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class SubjectSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = SubjectSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SubmissionSchema extends BaseModel {
  static $columns = ['assignmentId', 'content', 'createdAt', 'feedback', 'fileUrl', 'id', 'score', 'status', 'studentId', 'submittedAt', 'updatedAt'] as const
  $columns = SubmissionSchema.$columns
  @column()
  declare assignmentId: number | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare feedback: string | null
  @column()
  declare fileUrl: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: number | null
  @column()
  declare status: string | null
  @column()
  declare studentId: number | null
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TeacherSchema extends BaseModel {
  static $columns = ['createdAt', 'employeeNumber', 'hireDate', 'id', 'specialization', 'status', 'updatedAt', 'userId'] as const
  $columns = TeacherSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare employeeNumber: string
  @column.date()
  declare hireDate: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare specialization: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number | null
}

export class TeachingAssignmentSchema extends BaseModel {
  static $columns = ['academicYearId', 'classId', 'createdAt', 'id', 'subjectId', 'teacherId', 'updatedAt'] as const
  $columns = TeachingAssignmentSchema.$columns
  @column()
  declare academicYearId: number | null
  @column()
  declare classId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare subjectId: number | null
  @column()
  declare teacherId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['avatar', 'createdAt', 'email', 'firstName', 'fullName', 'id', 'isActive', 'lastName', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
